services:
  - type: web
    name: jilibot
    env: python
    buildCommand: |
      pyenv install 3.10.13
      pyenv global 3.10.13
      pip install -r requirements.txt
    startCommand: python jili.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
