services:
  - type: web
    name: jili-signal-bot
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        value: 6588452433:AAFf0uLB8y6wkA3hi0nU8o78HWla7wsdk9I
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    region: singapore
